### ISSUE TITLE
Feedback on AM9511

### ISSUE THREAD

**Issue by dmcnaugh** [ratboy666/am9511#2]
Fred,
Firstly - great work - I've had a lot of fun as you will see in my reply to your forum post.
if you haven't seen the reply to your post on the IMSAI8080esp forum https://groups.google.com/g/imsai8080esp/c/1xQNSCnUWcE/m/vPT0aYo2BQAJ

- Udo and I have now integrated your AM9511 simulation into Z80PACK, currently for the **imsaisim** IMSAI8080 simulator.
- Additionally I have also integrated into the **IMSAI8080esp** replica.
- Speed results are discussed in the forum post.
- But also of note is that XYBASIC has native support for the AM9511 if compiled with that option.

---
A couple of points also for you to take a look at:
1. it might be worth organising the files in this repo into some functional folders eg. `src`, `test` to clearly indicate what belongs with what
2. I cannot successfully use the `testhw.com` (and others) under CP/M 2.2 as I get the following output:

```
I>testhw -d162 -s163
test am9511: am9511
am9511: illegal option -- D
usage: am9511 [-d port] [-s port]
    -d port    set data port
    -s port    set status port

port numbers are specified in decimal
```
looks like it is seeing an upper-D for the option flag and not accepting it.

**Comment by ratboy666** [comment]
Wow -- thanks for the report. Yes, oversight on my part. I used BSD getopt, and that works, ...but... since I test with Zxcc, it uses case-sensitive options! "zxcc testhw --d65" works fine, but "zxcc testhw --D65" won't.

As to organizing into directories - If it gets much bigger, then yes. But... I split apu support libraries into their
own project. The next big thing for am9511 is to make it use "chip accurate algorithms" (using chebyshev like
the chip does). Any re-org can wait for that (in my opinion).

-s and -d fixed.

Fred
